### ISSUE TITLE
Implement Summary and Steps

### ISSUE THREAD

**Issue by nicklandgrebe** [GetOccasion/modern-checkout#1]
## Stories

* As a customer, I want to be able to see a summary of the order I'm making and the current step I am on while booking

## Implementation

Create a `Summary` component that displays certain aspects of the order
Create a `Steps` component that displays the current step

## TODOs

- [ ] Create Summary component with time slot output
- [x] Add `incrementStep` action with `step` state variable
- [ ] Create Steps component that displays current step
